// Generated by scripts/build-library.mjs — do not edit.
// Source of truth is content/. Run `npm run library:build` after changing it.

import type { Echo, Route } from "@echofinders/core";

// DEMO ONLY: editorial status is overridden to "approved" so the prototype has
// something to play. The real library in content/ is untouched and still awaiting
// human fact-checking. Never import this into anything that ships.
export const LIBRARY: readonly Echo[] = [
  {
    "id": "african-burial-ground",
    "title": "What the excavation found in 1991",
    "summary": "A federal building site uncovered the largest known African burial ground in North America.",
    "point": {
      "at": {
        "lat": 40.71455,
        "lng": -74.00437
      },
      "triggerRadiusKm": 0.07,
      "place": "African Burial Ground, Duane Street, Manhattan"
    },
    "category": "history",
    "format": "short",
    "durationS": 110,
    "minAge": 10,
    "quality": 0.95,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "African Burial Ground National Monument",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nps.gov/afbg/index.htm"
      },
      {
        "title": "New York — African Burial Ground National Monument",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nps.gov/articles/afamburial.htm"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "In 1991 the federal government began digging foundations for an office tower at Broadway\nand Duane, and about seven metres down the crews found bone.\n\nWhat lay beneath the block was a cemetery. From the late sixteen-hundreds into the\nseventeen-nineties, free and enslaved Africans in this city had buried their dead in a\npatch of ground outside the settlement's boundary — roughly six and a half acres of it.\nLater New York built over the site and forgot. Estimates put the number of burials around\nfifteen thousand.\n\nFour hundred and nineteen men, women and children were recovered from the part that was\nexcavated. Their descendants and this city's Black community fought to stop the\nconstruction, and won. The remains were studied, then reinterred here in 2003.\n\nIt is the earliest and largest African burial ground yet found in the United States, and\nit existed partly because of a rule: from 1697, Africans were barred from the city's main\nburial ground. So they made their own, out past the edge of town.\n\nYou are standing at the edge of town.\n",
    "teaser": "Twenty-four feet below the pavement.",
    "detail": "The memorial occupies a fraction of the original site; most of the burial ground remains\nunder the surrounding streets and buildings. It was designated a National Monument in\n2006.\n",
    "voice": "plP9aw1rizYgjFfuvLQ7",
    "pronunciations": [
      {
        "written": "Duane Street",
        "say": "doo-AYN Street"
      },
      {
        "written": "reinterred",
        "say": "ree-in-TERD"
      }
    ],
    "tags": [
      "new-york",
      "slavery",
      "archaeology",
      "memorial"
    ]
  },
  {
    "id": "bowling-green-king-george",
    "title": "They pulled the king down and made him into bullets",
    "summary": "A crowd toppled a gilded statue of George III here in 1776 and melted it into musket balls.",
    "point": {
      "at": {
        "lat": 40.70463,
        "lng": -74.01319
      },
      "triggerRadiusKm": 0.06,
      "place": "Bowling Green, Manhattan"
    },
    "category": "history",
    "format": "short",
    "durationS": 90,
    "minAge": 0,
    "quality": 0.9,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "Bowling Green",
        "publisher": "NYC Parks",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nycgovparks.org/parks/bowling-green/history"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "This is the oldest public park in the city, and the fence around it has been here since\n1771.\n\nLook at the tops of the posts. They used to have small crowns on them.\n\nOn the ninth of July 1776, the Declaration of Independence was read aloud to Washington's\ntroops a few streets north of here. The crowd came down to this green afterwards, where a\ngilded lead statue of King George the Third sat on horseback, and pulled it down.\n\nThe lead went to Connecticut and came back as musket balls. Somebody, at some point, took\na saw to the crowns on the fence.\n\nTwo hundred and fifty years later the fence is still standing and the crowns are still\nmissing, which is a fairly direct way of making a point.\n",
    "teaser": "The fence is original. Look at the tops of the posts.",
    "voice": "hP72SDESIJq2YuAblBqz",
    "pronunciations": [
      {
        "written": "Bowling Green",
        "say": "BOH-ling Green"
      }
    ],
    "tags": [
      "new-york",
      "revolution",
      "statues",
      "protest"
    ]
  },
  {
    "id": "canyon-of-heroes",
    "title": "A canyon named after confetti",
    "summary": "Granite strips in the pavement name every ticker-tape parade since 1886.",
    "point": {
      "at": {
        "lat": 40.7098,
        "lng": -74.0108
      },
      "triggerRadiusKm": 0.12,
      "place": "Broadway, the Canyon of Heroes, Manhattan"
    },
    "category": "culture-food",
    "format": "short",
    "durationS": 55,
    "minAge": 0,
    "quality": 0.82,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "Canyon of Heroes",
        "publisher": "Downtown Alliance",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain",
        "url": "https://downtownny.com/canyon-of-heroes/"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "Look down at the pavement.\n\nSet into it along this stretch of Broadway are thin strips of granite, each one naming a\ndate and a person. There are more than two hundred of them.\n\nEvery strip is a ticker-tape parade. The first was in 1886, for the dedication of the\nStatue of Liberty, and nobody organised it — clerks in the offices above started throwing\nthe used tape from their stock tickers out of the windows, because they could not think\nof anything better to do.\n\nNobody has used ticker tape since the 1960s. They shred paper for it now.\n\nSo this is a canyon named after confetti, which was named after rubbish.\n",
    "teaser": "Look down at the pavement.",
    "voice": "plP9aw1rizYgjFfuvLQ7",
    "tags": [
      "new-york",
      "parades",
      "broadway"
    ]
  },
  {
    "id": "casa-casuarina-the-steps",
    "title": "He did not get through the door",
    "summary": "Gianni Versace was killed on these steps in 1997, coming back from breakfast.",
    "point": {
      "at": {
        "lat": 25.7837,
        "lng": -80.12985
      },
      "triggerRadiusKm": 0.03,
      "place": "Casa Casuarina, 1116 Ocean Drive, Miami Beach"
    },
    "category": "true-crime",
    "format": "short",
    "durationS": 100,
    "minAge": 16,
    "quality": 0.9,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "Andrew Phillip Cunanan — Ten Most Wanted Fugitives case record",
        "publisher": "Federal Bureau of Investigation",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain"
      },
      {
        "title": "Incident and investigative record, 1116 Ocean Drive, 15 July 1997",
        "publisher": "Miami Beach Police Department",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain"
      },
      {
        "title": "Medical examiner's report, Gianni Versace",
        "publisher": "Miami-Dade County Medical Examiner",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "Look at the steps in front of the gate. Not the house — the steps.\n\nAt about a quarter to nine on the morning of the fifteenth of July, nineteen ninety-seven,\nGianni Versace came back up Ocean Drive carrying his magazines and stopped here to open\nhis own front door.\n\nA man walked up behind him and fired twice. Versace was fifty. He did not get through the\ndoor.\n\nPolice identified the man who shot him as Andrew Cunanan, already on the FBI's Ten Most\nWanted list. Eight days later Cunanan was found dead on a houseboat two miles north of\nwhere you are standing. He was never tried. He left nothing behind explaining any of it,\nand no motive has ever been established.\n\nBy the time he reached Miami Beach, four other people were already dead. Jeffrey Trail.\nDavid Madson. Lee Miglin. William Reese.\n\nThis address is famous because of who died at it.\n\nNobody stands outside the other four.\n",
    "teaser": "Look at the steps in front of the gate. Not the house.",
    "voice": "plP9aw1rizYgjFfuvLQ7",
    "pronunciations": [
      {
        "written": "Versace",
        "say": "ver-SAH-chay"
      },
      {
        "written": "Casuarina",
        "say": "kazh-oo-a-REE-na"
      },
      {
        "written": "Cunanan",
        "say": "koo-NAN-an"
      }
    ],
    "tags": [
      "miami-beach",
      "ocean-drive",
      "versace"
    ],
    "trueCrimeReview": {
      "involvesLivingPeople": true,
      "convictionStatus": "alleged",
      "reviewedBy": "TODO — a named human, before this can leave draft. See the note below.",
      "reviewedAt": "2026-09-22",
      "contentWarning": "This echo describes a murder. No violence is described in detail."
    }
  },
  {
    "id": "castle-clinton-eight-million",
    "title": "Eight million people walked through this fort",
    "summary": "A harbour fort that became America's first immigration station, decades before Ellis Island.",
    "point": {
      "at": {
        "lat": 40.70331,
        "lng": -74.01705
      },
      "triggerRadiusKm": 0.09,
      "place": "Castle Clinton, Battery Park, Manhattan"
    },
    "category": "history",
    "format": "short",
    "durationS": 95,
    "minAge": 0,
    "quality": 0.88,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "Castle Clinton National Monument — History & Culture",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nps.gov/cacl/learn/historyculture/index.htm"
      },
      {
        "title": "Castle Clinton National Monument",
        "publisher": "Lower Manhattan Historical Association",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.historiclowermanhattan.org/immigration/castle-clinton-national-monument"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "The round sandstone building ahead of you was built to stop an invasion that never came.\n\nIt went up between 1808 and 1811, out on a small island off the tip of Manhattan, its\nguns pointed down the harbour at a British fleet everyone expected and nobody saw. The\nlandfill came later. So did almost everything else it has been.\n\nBecause in 1855 the fort became a door. On the first of August that year it opened as the\nEmigrant Landing Depot — the first immigration station in the United States, run by the\nState of New York — and over the next thirty-five years something like eight million\npeople walked through it and out into the rest of their lives. Nikola Tesla came through\nhere. So did Harry Houdini, and Emma Goldman, and Joseph Pulitzer.\n\nIn 1890 the federal government took the job over, and two years later moved it to a\nbigger island further out, where the ferries go now. The fort stayed, and became other\nthings again: a beer garden, a theatre, an aquarium.\n\nEight million arrivals, and almost nobody stops here. Most people walk past it to queue\nfor the boat.\n",
    "teaser": "Before Ellis Island, there was this.",
    "detail": "The fort has had at least five lives: coastal battery, public promenade and entertainment\nhall, immigration depot, city aquarium, and finally a national monument. Jenny Lind gave\nher first American concert in it in 1850.\n",
    "voice": "plP9aw1rizYgjFfuvLQ7",
    "pronunciations": [
      {
        "written": "Nikola Tesla",
        "say": "NEE-koh-lah TESS-lah"
      },
      {
        "written": "Emma Goldman",
        "say": "EM-uh GOLD-mun"
      }
    ],
    "tags": [
      "immigration",
      "new-york",
      "forts",
      "nineteenth-century"
    ]
  },
  {
    "id": "charging-bull-illegal",
    "title": "The bull was dumped here illegally in the night",
    "summary": "An artist installed three and a half tonnes of bronze outside the Stock Exchange without asking.",
    "point": {
      "at": {
        "lat": 40.70552,
        "lng": -74.0134
      },
      "triggerRadiusKm": 0.12,
      "place": "Bowling Green, Broadway, Manhattan"
    },
    "category": "culture-food",
    "format": "look-below",
    "durationS": 45,
    "minAge": 0,
    "quality": 0.8,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "Charging Bull",
        "publisher": "NYC Parks",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nycgovparks.org/parks/bowling-green/monuments/1780"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "Nobody commissioned this.\n\nIn December 1989, two years after the crash, a sculptor called Arturo Di Modica drove a\nlorry to Wall Street in the middle of the night and left three and a half tonnes of bronze\noutside the Stock Exchange. He had paid for it himself. It was, legally speaking,\nfly-tipping.\n\nThe city removed it within hours. The public objected loudly enough that it was put back a\nfew days later, here, a couple of streets from where he left it — on a temporary permit\nthat has now lasted more than thirty years.\n",
    "teaser": "Nobody gave permission for this.",
    "voice": "plP9aw1rizYgjFfuvLQ7",
    "pronunciations": [
      {
        "written": "Arturo Di Modica",
        "say": "ar-TOO-roh dee MOH-dee-kah"
      }
    ],
    "tags": [
      "new-york",
      "art",
      "wall-street"
    ]
  },
  {
    "id": "city-hall-declaration",
    "title": "What the army did after they heard it",
    "summary": "Washington had the Declaration read to his troops here. They did not stay to discuss it.",
    "point": {
      "at": {
        "lat": 40.7127,
        "lng": -74.006
      },
      "triggerRadiusKm": 0.1,
      "place": "City Hall Park, Manhattan"
    },
    "category": "history",
    "format": "short",
    "durationS": 95,
    "minAge": 0,
    "quality": 0.93,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "City Hall Park",
        "publisher": "NYC Parks",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain",
        "url": "https://www.nycgovparks.org/parks/city-hall-park/history"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "This was not a park. It was the Common — the rough field outside town where you put the\nthings nobody wanted near them. A poorhouse. A prison. A gallows.\n\nOn the ninth of July 1776, George Washington had his army formed up on this ground, in\nsquares, and had an officer read out a document that had arrived from Philadelphia five\ndays earlier.\n\nThere is no record of the soldiers being told to do anything afterwards.\n\nWhat they did was walk down Broadway, about a mile, to the little green at the bottom of\nthe island, and pull a two-ton gilded statue of the king off its plinth.\n\nWashington was not pleased. He put out an order the next morning calling it disorderly,\nand asking that in future such matters be left to the proper authorities.\n\nThe war he had just read them into lasted another seven years.\n",
    "teaser": "This was not a park.",
    "voice": "hP72SDESIJq2YuAblBqz",
    "tags": [
      "new-york",
      "revolution",
      "washington"
    ]
  },
  {
    "id": "dakota-three-minutes",
    "title": "Three minutes from here",
    "summary": "John Lennon was killed in this archway in 1980. His memorial is across the street.",
    "point": {
      "at": {
        "lat": 40.77625,
        "lng": -73.97596
      },
      "triggerRadiusKm": 0.04,
      "place": "The Dakota, 1 West 72nd Street, Manhattan"
    },
    "category": "true-crime",
    "format": "short",
    "durationS": 110,
    "minAge": 16,
    "quality": 0.92,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "People v. Chapman — conviction and sentence, New York Supreme Court, 1981",
        "publisher": "New York State Unified Court System",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain"
      },
      {
        "title": "Parole Board hearing transcripts, Mark David Chapman",
        "publisher": "New York State Board of Parole",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "Look across the street, into the park. Those trees are Strawberry Fields. It is about a\nthree-minute walk, and you are going to make it in a moment.\n\nBehind you is the Dakota. John Lennon lived here with Yoko Ono and their son. Yoko Ono\nlives here still — this is not a monument, it is a building full of people's homes, so\nstay on the pavement and keep out of the archway.\n\nOn the eighth of December nineteen eighty, at around ten to eleven at night, Lennon came\nback from a recording session. He walked from the car towards that arch. A man who had\nbeen waiting near the entrance since the afternoon fired five shots, and four of them hit\nhim. Earlier the same day, Lennon had signed a record for him.\n\nThe police did not wait for an ambulance. They put him in the back of a patrol car and\ndrove him to Roosevelt Hospital, where he was pronounced dead. He was forty.\n\nThere is no marker here. There was never going to be one.\n\nCross at the lights and walk into the park.\n",
    "teaser": "Look across the street, into the park.",
    "voice": "hP72SDESIJq2YuAblBqz",
    "pronunciations": [
      {
        "written": "Dakota",
        "say": "duh-KOH-ta"
      }
    ],
    "tags": [
      "new-york",
      "upper-west-side",
      "lennon",
      "memorial"
    ],
    "trueCrimeReview": {
      "involvesLivingPeople": true,
      "convictionStatus": "convicted",
      "reviewedBy": "TODO — a named human, before this can leave draft. See the note below.",
      "reviewedAt": "2026-09-22",
      "contentWarning": "This echo describes a murder. No violence is described in detail."
    }
  },
  {
    "id": "federal-hall-two-firsts",
    "title": "Two American firsts happened on this corner",
    "summary": "A free press was won here in 1735, and the first president sworn in on the balcony in 1789.",
    "point": {
      "at": {
        "lat": 40.70733,
        "lng": -74.01001
      },
      "triggerRadiusKm": 0.06,
      "place": "Federal Hall, 26 Wall Street, Manhattan"
    },
    "category": "history",
    "format": "short",
    "durationS": 105,
    "minAge": 0,
    "quality": 0.9,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "The Trial of John Peter Zenger",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nps.gov/feha/learn/historyculture/the-trial-of-john-peter-zenger.htm"
      },
      {
        "title": "Federal Hall National Memorial",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nps.gov/feha/index.htm"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "Stand facing the columns, and know first that this is not the building.\n\nThe one that mattered was New York's City Hall, and it stood on this exact spot. Two\nthings happened in it that the country is still living inside.\n\nIn 1735 a printer named John Peter Zenger was tried here for libel. He had published\ncriticism of the royal governor in his newspaper, and under the law of the time truth was\nno defence — printing it was the crime, whether or not it was accurate. The jury\nacquitted him anyway. It was not yet law, but it was the beginning of the argument that\nbecame a free press.\n\nFifty-four years later the same site, rebuilt as Federal Hall, was the first Capitol of\nthe United States. On the thirtieth of April 1789, George Washington stepped onto a\nbalcony above this street and took the oath as the first president, in front of a crowd\nfilling Wall Street below you.\n\nThat building was demolished in 1812. What you are looking at went up in 1842, as a\ncustoms house. The statue of Washington faces the street, roughly where the balcony was.\n",
    "teaser": "The building is not the one it happened in. The corner is.",
    "voice": "plP9aw1rizYgjFfuvLQ7",
    "pronunciations": [
      {
        "written": "John Peter Zenger",
        "say": "ZENG-er"
      },
      {
        "written": "Houston Street",
        "say": "HOW-ston Street",
        "ipa": "ˈhaʊstən"
      }
    ],
    "tags": [
      "new-york",
      "founding",
      "press-freedom",
      "wall-street"
    ]
  },
  {
    "id": "fraunces-tavern-farewell",
    "title": "The goodbye that nobody got through",
    "summary": "Washington said farewell to his officers in an upstairs room here in December 1783.",
    "point": {
      "at": {
        "lat": 40.70353,
        "lng": -74.01133
      },
      "triggerRadiusKm": 0.05,
      "place": "Fraunces Tavern, Pearl Street, Manhattan"
    },
    "category": "history",
    "format": "short",
    "durationS": 85,
    "minAge": 0,
    "quality": 0.85,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "Fraunces Tavern and the Continental Army",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nps.gov/articles/fraunces-tavern.htm"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "On the fourth of December 1783, in an upstairs room of this building, George Washington\nsaid goodbye to the officers he had fought beside for eight years.\n\nThe British had sailed out of the harbour nine days earlier. The war was over, and he was\ngoing home to Virginia, believing he was finished with public life.\n\nBy the accounts that survive, he could not finish what he meant to say. He raised a glass,\nmanaged a few sentences, and then asked each man to come and take his hand. Grown soldiers\nwept. He walked out without trusting himself to speak again.\n\nSix years later he was back in this city, taking an oath three streets from here.\n",
    "teaser": "Upstairs, in the Long Room.",
    "voice": "hP72SDESIJq2YuAblBqz",
    "tags": [
      "new-york",
      "revolution",
      "washington"
    ]
  },
  {
    "id": "news-cafe-last-ordinary-morning",
    "title": "The last ordinary hour",
    "summary": "He came here most mornings that summer, bought magazines, and walked home.",
    "point": {
      "at": {
        "lat": 25.78013,
        "lng": -80.13003
      },
      "triggerRadiusKm": 0.03,
      "place": "News Café, 800 Ocean Drive, Miami Beach"
    },
    "category": "true-crime",
    "format": "short",
    "durationS": 65,
    "minAge": 16,
    "quality": 0.85,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "Andrew Phillip Cunanan — Ten Most Wanted Fugitives case record",
        "publisher": "Federal Bureau of Investigation",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain"
      },
      {
        "title": "Incident and investigative record, 1116 Ocean Drive, 15 July 1997",
        "publisher": "Miami Beach Police Department",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain"
      },
      {
        "title": "Medical examiner's report, Gianni Versace",
        "publisher": "Miami-Dade County Medical Examiner",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "You are outside a café that has been on this corner since the middle of the eighties.\n\nIn the summer of nineteen ninety-seven a man came down here most mornings from a house\nthree blocks north. He sat outside. He bought a stack of magazines. The staff knew him by\nsight, the way staff know a regular.\n\nOn the fifteenth of July he did exactly that, and then he walked home.\n\nHis name was Gianni Versace, and this was the last ordinary hour of his life.\n\nIt is four blocks north along the beach side. About six minutes.\n\nTake it slowly. He did.\n",
    "teaser": "A café, a stack of magazines, and a four-block walk north.",
    "voice": "plP9aw1rizYgjFfuvLQ7",
    "pronunciations": [
      {
        "written": "Versace",
        "say": "ver-SAH-chay"
      }
    ],
    "tags": [
      "miami-beach",
      "ocean-drive",
      "versace"
    ],
    "trueCrimeReview": {
      "involvesLivingPeople": true,
      "convictionStatus": "alleged",
      "reviewedBy": "TODO — a named human, before this can leave draft. See the note below.",
      "reviewedAt": "2026-09-22",
      "contentWarning": "This echo describes a murder. No violence is described in detail."
    }
  },
  {
    "id": "pearl-street-oysters",
    "title": "A street paved with rubbish",
    "summary": "Pearl Street is white underneath because people threw their lunch on the ground.",
    "point": {
      "at": {
        "lat": 40.7038,
        "lng": -74.0112
      },
      "triggerRadiusKm": 0.09,
      "place": "Pearl Street, Manhattan"
    },
    "category": "kids",
    "format": "short",
    "durationS": 85,
    "minAge": 0,
    "quality": 0.9,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "What in the Pearl? A History of NYC's Oysters",
        "publisher": "Downtown Alliance",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain",
        "url": "https://downtownny.com/news/oyster-history-downtown/"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "You are standing on a street that was paved with rubbish.\n\nLook at the name. Pearl Street. The Dutch called it that because the ground here was\nwhite — not with stone, but with oyster shells. Millions of them, crushed flat and\ntrodden down until they made a road.\n\nFour hundred years ago, the water around this island held about half of all the oysters\nin the world. Three hundred and fifty square miles of oyster beds. Some of the oysters\nwere as big as a dinner plate.\n\nThere were so many that they were cheap, so everybody ate them. Not in restaurants — from\ncarts in the street, the way you might buy a hot dog now. You ate the oyster, and you\nthrew the shell on the ground.\n\nEnough people did that, for enough years, that the shells became the street.\n\nOne more thing. The Dutch kept opening them to look for pearls. They never found a single\none. New York oysters don't make them.\n",
    "teaser": "Why is it called Pearl Street?",
    "voice": "MkTSSXNgnBULS6ek4pon",
    "tags": [
      "new-york",
      "oysters",
      "food",
      "dutch"
    ]
  },
  {
    "id": "st-pauls-still-standing",
    "title": "The building that keeps not burning down",
    "summary": "Manhattan's oldest public building in continuous use, and what stood between it and the towers.",
    "point": {
      "at": {
        "lat": 40.7112,
        "lng": -74.0092
      },
      "triggerRadiusKm": 0.08,
      "place": "St Paul's Chapel, Broadway, Manhattan"
    },
    "category": "history",
    "format": "short",
    "durationS": 100,
    "minAge": 12,
    "quality": 0.94,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "St Paul's Chapel",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain",
        "url": "https://www.nps.gov/places/st-paul-s-chapel.htm"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "This is the oldest public building in Manhattan still doing the thing it was built to do.\n\nIt went up in 1766, when this was the northern edge of town and the front of the chapel\nfaced the river, because that was the direction people arrived from.\n\nTen years later a fire took a quarter of the city and stopped at its churchyard.\n\nGeorge Washington came here on the day he was inaugurated, and kept coming for the two\nyears New York was the capital. His pew is still inside.\n\nOn the eleventh of September 2001, the towers came down about a hundred metres from where\nyou are standing. Every window in this chapel survived. For eight months afterwards it\nwas where the recovery workers slept and ate and had their feet seen to.\n\nA sycamore tree in the churchyard took the weight of the debris that would otherwise have\nhit the building. It did not survive. The chapel did.\n",
    "teaser": "The oldest building in Manhattan still doing its job.",
    "voice": "hP72SDESIJq2YuAblBqz",
    "pronunciations": [
      {
        "written": "sycamore",
        "say": "SIK-a-more"
      }
    ],
    "tags": [
      "new-york",
      "churches",
      "washington",
      "september-11"
    ]
  },
  {
    "id": "strawberry-fields-one-word",
    "title": "One word on the ground",
    "summary": "The memorial Yoko Ono chose instead of a statue, three minutes from where he died.",
    "point": {
      "at": {
        "lat": 40.77541,
        "lng": -73.97461
      },
      "triggerRadiusKm": 0.04,
      "place": "Imagine mosaic, Strawberry Fields, Central Park"
    },
    "category": "true-crime",
    "format": "short",
    "durationS": 70,
    "minAge": 16,
    "quality": 0.9,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "People v. Chapman — conviction and sentence, New York Supreme Court, 1981",
        "publisher": "New York State Unified Court System",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain"
      },
      {
        "title": "Strawberry Fields — landscape and memorial record",
        "publisher": "NYC Parks",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "Stop at the mosaic and look down.\n\nOne word. The mosaic was a gift from the city of Naples.\n\nTurn around. Through the trees, you can still see the Dakota. You walked it in three\nminutes.\n\nThe city named this part of the park after a song rather than after a man. Yoko Ono wanted\na landscape instead of a statue, and she wanted it dedicated to peace rather than to what\nhappened across the road.\n\nSo there are two places, three minutes apart.\n\nOne is where he died. It is unmarked, and people live there.\n\nThe other is a word on the ground, and strangers sit around it all day.\n\nShe chose which one to build.\n",
    "teaser": "Stop at the mosaic and look down.",
    "voice": "hP72SDESIJq2YuAblBqz",
    "tags": [
      "new-york",
      "central-park",
      "lennon",
      "memorial"
    ],
    "trueCrimeReview": {
      "involvesLivingPeople": true,
      "convictionStatus": "convicted",
      "reviewedBy": "TODO — a named human, before this can leave draft. See the note below.",
      "reviewedAt": "2026-09-22",
      "contentWarning": "This echo describes a murder. No violence is described in detail."
    }
  },
  {
    "id": "trinity-tallest-thing",
    "title": "For forty-four years this was the tallest thing in New York",
    "summary": "Sailors coming into the harbour saw the spire before they saw the city.",
    "point": {
      "at": {
        "lat": 40.7081,
        "lng": -74.0122
      },
      "triggerRadiusKm": 0.08,
      "place": "Trinity Church, Broadway and Wall Street, Manhattan"
    },
    "category": "famous-people",
    "format": "short",
    "durationS": 85,
    "minAge": 0,
    "quality": 0.85,
    "visibility": "landmark-visible",
    "certainty": "documented",
    "sources": [
      {
        "title": "Trinity Church",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain",
        "url": "https://www.nps.gov/places/trinity-church.htm"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "Look up at the spire.\n\nFor forty-four years that was the highest point in New York. Not the tallest church — the\ntallest anything. Ships coming into the harbour saw it before they saw the city.\n\nIt went up in 1846. Two hundred and eighty-one feet, and nothing in this city passed it\nuntil 1890.\n\nWhich means there was a stretch of time, right here, when the largest thing people in New\nYork were willing to build was somewhere to pray.\n\nWhat passed it was a newspaper office. What passed that was an insurance company. Then\nthe banks arrived, and they have not stopped.\n\nAlexander Hamilton is buried in the yard on your right. He was killed in 1804, so he\nnever saw this building — he is lying beside the third church on this spot, in a\ngraveyard that outlasted two of them.\n",
    "teaser": "Look up at the spire.",
    "voice": "plP9aw1rizYgjFfuvLQ7",
    "tags": [
      "new-york",
      "architecture",
      "hamilton"
    ]
  },
  {
    "id": "wall-street-the-wall",
    "title": "The street is named after something that isn't there",
    "summary": "A nine-foot palisade crossed the island here, built mostly by people who were not free.",
    "point": {
      "at": {
        "lat": 40.7074,
        "lng": -74.011
      },
      "triggerRadiusKm": 0.1,
      "place": "Wall Street, Manhattan"
    },
    "category": "history",
    "format": "short",
    "durationS": 90,
    "minAge": 10,
    "quality": 0.92,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "Anniversary of Wall Street",
        "publisher": "NYC Department of Records & Information Services",
        "retrievedAt": "2026-09-22",
        "rights": "public-domain",
        "url": "https://www.archives.nyc/blog/2023/3/9/anniversary-of-wall-street"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "Look down the street. It runs river to river — you can very nearly see one end from the\nother.\n\nThat is not an accident. It is the width of the island, and in 1653 the Dutch decided to\nfence it off.\n\nThe governor, Peter Stuyvesant, ordered a palisade built right across here. Nine feet\nhigh, made of packed earth and fifteen-foot planks, running from the Hudson to the East\nRiver. It was meant to stop an English invasion.\n\nThe people who built it were mostly enslaved Africans, owned by the Dutch West India\nCompany.\n\nThe invasion never came. The English took the colony anyway, eleven years later, by\nsailing in and asking. And in 1699 they pulled the wall down and used the wood for\nsomething else.\n\nIt stood for forty-six years. It has been gone for more than three hundred.\n\nThe street kept the name — which means this is a street named after a thing that is not\nthere, put up by people who were never free to walk away from it.\n",
    "teaser": "Look down the street. It runs river to river.",
    "voice": "hP72SDESIJq2YuAblBqz",
    "pronunciations": [
      {
        "written": "Peter Stuyvesant",
        "say": "STY-ve-sant"
      }
    ],
    "tags": [
      "new-york",
      "dutch",
      "slavery",
      "wall-street"
    ]
  }
] as const;

export const ROUTE: Route = {
  "id": "lower-manhattan-walk",
  "mode": "walking",
  "origin": {
    "name": "Battery Park",
    "at": {
      "lat": 40.7033,
      "lng": -74.017
    },
    "timeZone": "America/New_York"
  },
  "destination": {
    "name": "African Burial Ground",
    "at": {
      "lat": 40.7145,
      "lng": -74.0044
    },
    "timeZone": "America/New_York"
  },
  "waypoints": [
    {
      "name": "Battery Park",
      "at": {
        "lat": 40.7033,
        "lng": -74.017
      }
    },
    {
      "name": "Bowling Green",
      "at": {
        "lat": 40.7046,
        "lng": -74.0132
      },
      "dwellS": 240
    },
    {
      "name": "Fraunces Tavern",
      "at": {
        "lat": 40.7036,
        "lng": -74.0112
      },
      "dwellS": 240
    },
    {
      "name": "Federal Hall",
      "at": {
        "lat": 40.7073,
        "lng": -74.01
      },
      "dwellS": 240
    },
    {
      "name": "Trinity Church",
      "at": {
        "lat": 40.7081,
        "lng": -74.0122
      },
      "dwellS": 150
    },
    {
      "name": "Canyon of Heroes",
      "at": {
        "lat": 40.7098,
        "lng": -74.0108
      },
      "dwellS": 120
    },
    {
      "name": "St Paul's Chapel",
      "at": {
        "lat": 40.7112,
        "lng": -74.0092
      },
      "dwellS": 130
    },
    {
      "name": "City Hall Park",
      "at": {
        "lat": 40.7127,
        "lng": -74.006
      },
      "dwellS": 130
    },
    {
      "name": "African Burial Ground",
      "at": {
        "lat": 40.7145,
        "lng": -74.0044
      }
    }
  ],
  "durationS": 3000,
  "departureAt": "2026-06-15T14:00:00Z"
} as const;
