// Generated by scripts/build-library.mjs — do not edit.
// Source of truth is content/. Run `npm run library:build` after changing it.

import type { Echo, Route } from "@echofinders/core";

// DEMO ONLY: editorial status is overridden to "approved" so the prototype has
// something to play. The real library in content/ is untouched and still awaiting
// human fact-checking. Never import this into anything that ships.
export const LIBRARY: readonly Echo[] = [
  {
    "id": "african-burial-ground",
    "title": "What the excavation found in 1991",
    "summary": "A federal building site uncovered the largest known African burial ground in North America.",
    "point": {
      "at": {
        "lat": 40.71455,
        "lng": -74.00437
      },
      "triggerRadiusKm": 0.07,
      "place": "African Burial Ground, Duane Street, Manhattan"
    },
    "category": "history",
    "format": "short",
    "durationS": 110,
    "minAge": 10,
    "quality": 0.95,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "African Burial Ground National Monument",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nps.gov/afbg/index.htm"
      },
      {
        "title": "New York — African Burial Ground National Monument",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nps.gov/articles/afamburial.htm"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "In 1991 the federal government began digging foundations for an office tower at Broadway\nand Duane, and about seven metres down the crews found bone.\n\nWhat lay beneath the block was a cemetery. From the late sixteen-hundreds into the\nseventeen-nineties, free and enslaved Africans in this city had buried their dead in a\npatch of ground outside the settlement's boundary — roughly six and a half acres of it.\nLater New York built over the site and forgot. Estimates put the number of burials around\nfifteen thousand.\n\nFour hundred and nineteen men, women and children were recovered from the part that was\nexcavated. Their descendants and this city's Black community fought to stop the\nconstruction, and won. The remains were studied, then reinterred here in 2003.\n\nIt is the earliest and largest African burial ground yet found in the United States, and\nit existed partly because of a rule: from 1697, Africans were barred from the city's main\nburial ground. So they made their own, out past the edge of town.\n\nYou are standing at the edge of town.\n",
    "teaser": "Twenty-four feet below the pavement.",
    "detail": "The memorial occupies a fraction of the original site; most of the burial ground remains\nunder the surrounding streets and buildings. It was designated a National Monument in\n2006.\n",
    "pronunciations": [
      {
        "written": "Duane Street",
        "say": "doo-AYN Street"
      },
      {
        "written": "reinterred",
        "say": "ree-in-TERD"
      }
    ],
    "tags": [
      "new-york",
      "slavery",
      "archaeology",
      "memorial"
    ]
  },
  {
    "id": "bowling-green-king-george",
    "title": "They pulled the king down and made him into bullets",
    "summary": "A crowd toppled a gilded statue of George III here in 1776 and melted it into musket balls.",
    "point": {
      "at": {
        "lat": 40.70463,
        "lng": -74.01319
      },
      "triggerRadiusKm": 0.06,
      "place": "Bowling Green, Manhattan"
    },
    "category": "history",
    "format": "short",
    "durationS": 90,
    "minAge": 0,
    "quality": 0.9,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "Bowling Green",
        "publisher": "NYC Parks",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nycgovparks.org/parks/bowling-green/history"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "This is the oldest public park in the city, and the fence around it has been here since\n1771.\n\nLook at the tops of the posts. They used to have small crowns on them.\n\nOn the ninth of July 1776, the Declaration of Independence was read aloud to Washington's\ntroops a few streets north of here. The crowd came down to this green afterwards, where a\ngilded lead statue of King George the Third sat on horseback, and pulled it down.\n\nThe lead went to Connecticut and came back as musket balls. Somebody, at some point, took\na saw to the crowns on the fence.\n\nTwo hundred and fifty years later the fence is still standing and the crowns are still\nmissing, which is a fairly direct way of making a point.\n",
    "teaser": "The fence is original. Look at the tops of the posts.",
    "pronunciations": [
      {
        "written": "Bowling Green",
        "say": "BOH-ling Green"
      }
    ],
    "tags": [
      "new-york",
      "revolution",
      "statues",
      "protest"
    ]
  },
  {
    "id": "castle-clinton-eight-million",
    "title": "Eight million people walked through this fort",
    "summary": "A harbour fort that became America's first immigration station, decades before Ellis Island.",
    "point": {
      "at": {
        "lat": 40.70331,
        "lng": -74.01705
      },
      "triggerRadiusKm": 0.09,
      "place": "Castle Clinton, Battery Park, Manhattan"
    },
    "category": "history",
    "format": "short",
    "durationS": 95,
    "minAge": 0,
    "quality": 0.88,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "Castle Clinton National Monument — History & Culture",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nps.gov/cacl/learn/historyculture/index.htm"
      },
      {
        "title": "Castle Clinton National Monument",
        "publisher": "Lower Manhattan Historical Association",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.historiclowermanhattan.org/immigration/castle-clinton-national-monument"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "The round sandstone building ahead of you was built to stop an invasion that never came.\n\nIt went up between 1808 and 1811, out on a small island off the tip of Manhattan, its\nguns pointed down the harbour at a British fleet everyone expected and nobody saw. The\nlandfill came later. So did almost everything else it has been.\n\nBecause in 1855 the fort became a door. On the first of August that year it opened as the\nEmigrant Landing Depot — the first immigration station in the United States, run by the\nState of New York — and over the next thirty-five years something like eight million\npeople walked through it and out into the rest of their lives. Nikola Tesla came through\nhere. So did Harry Houdini, and Emma Goldman, and Joseph Pulitzer.\n\nIn 1890 the federal government took the job over, and two years later moved it to a\nbigger island further out, where the ferries go now. The fort stayed, and became other\nthings again: a beer garden, a theatre, an aquarium.\n\nEight million arrivals, and almost nobody stops here. Most people walk past it to queue\nfor the boat.\n",
    "teaser": "Before Ellis Island, there was this.",
    "detail": "The fort has had at least five lives: coastal battery, public promenade and entertainment\nhall, immigration depot, city aquarium, and finally a national monument. Jenny Lind gave\nher first American concert in it in 1850.\n",
    "pronunciations": [
      {
        "written": "Nikola Tesla",
        "say": "NEE-koh-lah TESS-lah"
      },
      {
        "written": "Emma Goldman",
        "say": "EM-uh GOLD-mun"
      }
    ],
    "tags": [
      "immigration",
      "new-york",
      "forts",
      "nineteenth-century"
    ]
  },
  {
    "id": "charging-bull-illegal",
    "title": "The bull was dumped here illegally in the night",
    "summary": "An artist installed three and a half tonnes of bronze outside the Stock Exchange without asking.",
    "point": {
      "at": {
        "lat": 40.70552,
        "lng": -74.0134
      },
      "triggerRadiusKm": 0.05,
      "place": "Bowling Green, Broadway, Manhattan"
    },
    "category": "culture-food",
    "format": "look-below",
    "durationS": 45,
    "minAge": 0,
    "quality": 0.8,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "Charging Bull",
        "publisher": "NYC Parks",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nycgovparks.org/parks/bowling-green/monuments/1780"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "Nobody commissioned this.\n\nIn December 1989, two years after the crash, a sculptor called Arturo Di Modica drove a\nlorry to Wall Street in the middle of the night and left three and a half tonnes of bronze\noutside the Stock Exchange. He had paid for it himself. It was, legally speaking,\nfly-tipping.\n\nThe city removed it within hours. The public objected loudly enough that it was put back a\nfew days later, here, a couple of streets from where he left it — on a temporary permit\nthat has now lasted more than thirty years.\n",
    "teaser": "Nobody gave permission for this.",
    "pronunciations": [
      {
        "written": "Arturo Di Modica",
        "say": "ar-TOO-roh dee MOH-dee-kah"
      }
    ],
    "tags": [
      "new-york",
      "art",
      "wall-street"
    ]
  },
  {
    "id": "federal-hall-two-firsts",
    "title": "Two American firsts happened on this corner",
    "summary": "A free press was won here in 1735, and the first president sworn in on the balcony in 1789.",
    "point": {
      "at": {
        "lat": 40.70733,
        "lng": -74.01001
      },
      "triggerRadiusKm": 0.06,
      "place": "Federal Hall, 26 Wall Street, Manhattan"
    },
    "category": "history",
    "format": "short",
    "durationS": 105,
    "minAge": 0,
    "quality": 0.9,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "The Trial of John Peter Zenger",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nps.gov/feha/learn/historyculture/the-trial-of-john-peter-zenger.htm"
      },
      {
        "title": "Federal Hall National Memorial",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nps.gov/feha/index.htm"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "Stand facing the columns, and know first that this is not the building.\n\nThe one that mattered was New York's City Hall, and it stood on this exact spot. Two\nthings happened in it that the country is still living inside.\n\nIn 1735 a printer named John Peter Zenger was tried here for libel. He had published\ncriticism of the royal governor in his newspaper, and under the law of the time truth was\nno defence — printing it was the crime, whether or not it was accurate. The jury\nacquitted him anyway. It was not yet law, but it was the beginning of the argument that\nbecame a free press.\n\nFifty-four years later the same site, rebuilt as Federal Hall, was the first Capitol of\nthe United States. On the thirtieth of April 1789, George Washington stepped onto a\nbalcony above this street and took the oath as the first president, in front of a crowd\nfilling Wall Street below you.\n\nThat building was demolished in 1812. What you are looking at went up in 1842, as a\ncustoms house. The statue of Washington faces the street, roughly where the balcony was.\n",
    "teaser": "The building is not the one it happened in. The corner is.",
    "pronunciations": [
      {
        "written": "John Peter Zenger",
        "say": "ZENG-er"
      },
      {
        "written": "Houston Street",
        "say": "HOW-ston Street",
        "ipa": "ˈhaʊstən"
      }
    ],
    "tags": [
      "new-york",
      "founding",
      "press-freedom",
      "wall-street"
    ]
  },
  {
    "id": "fraunces-tavern-farewell",
    "title": "The goodbye that nobody got through",
    "summary": "Washington said farewell to his officers in an upstairs room here in December 1783.",
    "point": {
      "at": {
        "lat": 40.70353,
        "lng": -74.01133
      },
      "triggerRadiusKm": 0.05,
      "place": "Fraunces Tavern, Pearl Street, Manhattan"
    },
    "category": "history",
    "format": "short",
    "durationS": 85,
    "minAge": 0,
    "quality": 0.85,
    "visibility": "at-hand",
    "certainty": "documented",
    "sources": [
      {
        "title": "Fraunces Tavern and the Continental Army",
        "publisher": "National Park Service",
        "retrievedAt": "2026-09-21",
        "rights": "public-domain",
        "url": "https://www.nps.gov/articles/fraunces-tavern.htm"
      }
    ],
    "editorial": "approved",
    "factCheck": "corroborated",
    "script": "On the fourth of December 1783, in an upstairs room of this building, George Washington\nsaid goodbye to the officers he had fought beside for eight years.\n\nThe British had sailed out of the harbour nine days earlier. The war was over, and he was\ngoing home to Virginia, believing he was finished with public life.\n\nBy the accounts that survive, he could not finish what he meant to say. He raised a glass,\nmanaged a few sentences, and then asked each man to come and take his hand. Grown soldiers\nwept. He walked out without trusting himself to speak again.\n\nSix years later he was back in this city, taking an oath three streets from here.\n",
    "teaser": "Upstairs, in the Long Room.",
    "tags": [
      "new-york",
      "revolution",
      "washington"
    ]
  }
] as const;

export const ROUTE: Route = {
  "id": "lower-manhattan-walk",
  "mode": "walking",
  "origin": {
    "name": "Battery Park",
    "at": {
      "lat": 40.7033,
      "lng": -74.017
    },
    "timeZone": "America/New_York"
  },
  "destination": {
    "name": "City Hall Park",
    "at": {
      "lat": 40.7127,
      "lng": -74.006
    },
    "timeZone": "America/New_York"
  },
  "waypoints": [
    {
      "name": "Battery Park",
      "at": {
        "lat": 40.7033,
        "lng": -74.017
      }
    },
    {
      "name": "Bowling Green",
      "at": {
        "lat": 40.7046,
        "lng": -74.0132
      }
    },
    {
      "name": "Wall Street",
      "at": {
        "lat": 40.7069,
        "lng": -74.0113
      }
    },
    {
      "name": "Federal Hall",
      "at": {
        "lat": 40.7073,
        "lng": -74.01
      }
    },
    {
      "name": "St Paul's Chapel",
      "at": {
        "lat": 40.7115,
        "lng": -74.0077
      }
    },
    {
      "name": "City Hall Park",
      "at": {
        "lat": 40.7127,
        "lng": -74.006
      }
    }
  ],
  "durationS": 2400,
  "departureAt": "2026-06-15T14:00:00Z"
} as const;
